FROM node:0.10

MAINTAINER tktk8924 <myphone.tk@gmail.com>

# For installing Firefox
RUN echo 'deb http://packages.linuxmint.com debian import' >> /etc/apt/sources.list.d/linuxming.list
RUN apt-key adv --recv-key --keyserver keyserver.ubuntu.com 3EE67F3D0FF405B2

# For installing Chrome
#RUN apt-get install -y wget && \
#    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
#    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

RUN apt-get update -y -q
RUN apt-get install -y -q xvfb  firefox libXcomposite1 libasound2 libdbus-glib-1-2 libgtkglextmm-x11-1.2-0
#RUN apt-get install -y google-chrome-stable

ADD xvfb_init /etc/init.d/xvfb
RUN chmod a+x /etc/init.d/xvfb
ADD xvfb-daemon-run /usr/bin/xvfb-daemon-run
RUN chmod a+x /usr/bin/xvfb-daemon-run

WORKDIR /app
COPY ./ .

RUN npm install
RUN node_modules/.bin/bower --allow-root install

ENV DISPLAY :99

EXPOSE 8000
CMD /etc/init.d/xvfb start && \
    npm start
